package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/defeng-hub/ByOfficeAutomatic/server Begin; DO NOT EDIT.

	// Code generated by github.com/defeng-hub/ByOfficeAutomatic/server End; DO NOT EDIT.
}

