package txyun

import (
	"github.com/defeng-hub/ByOfficeAutomatic/server/service"
)

type ApiGroup struct {
	// Code generated by github.com/defeng-hub/ByOfficeAutomatic/server Begin; DO NOT EDIT.
	SmsHandler
	OssHandle
	// Code generated by github.com/defeng-hub/ByOfficeAutomatic/server End; DO NOT EDIT.
}

var (
	// TxyunService 引入腾讯云的service
	TxyunService = service.ServiceGroupApp.TxyunServiceGroup
)
