package txyun

import (
	"github.com/defeng-hub/ByOfficeAutomatic/server/api/v1/txyun/oss"
	"github.com/defeng-hub/ByOfficeAutomatic/server/api/v1/txyun/sms"
)

type ApiGroup struct {
	// Code generated by github.com/defeng-hub/ByOfficeAutomatic/server Begin; DO NOT EDIT.
	sms.SmsHandler
	oss.OssHandle
	// Code generated by github.com/defeng-hub/ByOfficeAutomatic/server End; DO NOT EDIT.
}
